import type { Metadata } from "next";
import { Alata, Lateef } from "next/font/google";
import "./globals.css";

const alata = Alata({
  variable: "--font-alata-sans",
  subsets: ["latin"],
  weight: ["400"],
});

const lateef = Lateef({
  variable: "--font-lateef-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "After Bites",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alata.variable} ${lateef.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
